/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.alvingao.wordcounter;

public class WordCounter {
    public static void main(String[] args) {
        System.out.println();
    }
}
